production: &production
  facebook:
    key: ENV['FACEBOOK_KEY']
    secret: ENV['FACEBOOK_SECRET']
  stripe_connect:
    client_id: ENV['STRIPE_CLIENT_ID']
    secret: ENV['STRIPE_SECRET']

development: &development
  <<: *production

test:
  <<: *development